defmodule Notary.DSL.Compile do
  @moduledoc """
  Syncs DSL spec modules to their generated `.tla`/`.cfg` files.

  Discovers modules compiled from `use Notary.DSL` (marker: `__notary_description__/0`),
  computes the target paths (`specs/<Name>.tla` + `.cfg`), and writes files when
  stale:

    * a file with the GENERATED marker is overwritten whenever its content
      differs from the fresh emission;
    * a file *without* the marker (hand-written) is never touched — a name
      collision with a DSL module fails loudly instead;
    * unchanged files are not rewritten (mtimes stay stable for watchers).

  The lock covers the *generated* files (they are what TLC checks and what a
  reviewer reads), after syncing: `mix notary.lock` always syncs first so the
  hashes describe the current DSL.
  """

  alias Notary.Config
  alias Notary.DSL.Description

  @marker_prefix "\\* GENERATED by Notary.DSL — do not edit; source: "

  @type result :: {:ok, [String.t()], [String.t()]} | {:error, Error.t()}

  @doc """
  Syncs every DSL module to `specs/`. Returns `{:ok, written, unchanged}` with
  the file paths written and skipped-because-current. Idempotent.
  """
  @spec sync(keyword()) :: result()
  def sync(opts \\ []) do
    specs_dir = Path.expand(Keyword.get(opts, :specs_dir, Config.specs_dir()))

    with {:ok, mods} <- modules(Keyword.get(opts, :app, app_name())) do
      if mods == [] do
        {:ok, [], []}
      else
        sync_modules(mods, specs_dir: specs_dir)
      end
    end
  end

  @doc """
  Syncs the given DSL modules to `specs_dir` (as `sync/1`, without app
  discovery — tests and tools pass modules directly).
  """
  @spec sync_modules([module()], keyword()) :: {:ok, [String.t()], [String.t()]}
  def sync_modules(mods, opts \\ []) do
    specs_dir = Path.expand(Keyword.get(opts, :specs_dir, Config.specs_dir()))

    written = Enum.map(mods, &write_module(&1, specs_dir))

    all_files = Enum.flat_map(mods, &Map.values(paths(&1, specs_dir)))
    written_set = MapSet.new(Enum.flat_map(written, &elem(&1, 0)))
    unchanged = Enum.reject(all_files, &MapSet.member?(written_set, &1))

    {:ok, Enum.flat_map(written, &elem(&1, 0)), unchanged}
  end

  # `Mix.app_name/0` landed in Elixir 1.14 as `mix`-only? It is private in
  # 1.20's Mix module; derive the name from the project config.
  defp app_name, do: Mix.Project.config() |> Keyword.fetch!(:app)

  @doc "The spec name each DSL module generates."
  @spec spec_name(module()) :: String.t()
  def spec_name(mod), do: mod.__notary_description__().name

  @doc "The generated .tla and .cfg paths for a DSL module."
  @spec paths(module(), String.t()) :: %{tla: String.t(), cfg: String.t()}
  def paths(mod, specs_dir \\ Config.specs_dir()) do
    name = spec_name(mod)

    %{
      tla: Path.join(specs_dir, "#{name}.tla"),
      cfg: Path.join(specs_dir, "#{name}.cfg")
    }
  end

  # -- internals ----------------------------------------------------------------

  defp modules(app) do
    case ensure_loaded(app) do
      {:halted, []} ->
        {:ok, []}

      :ok ->
        mods =
          for module <- Application.spec(app, :modules) || [],
              Code.ensure_loaded?(module),
              function_exported?(module, :__notary_description__, 0),
              do: module

        {:ok, Enum.sort(mods)}
    end
  rescue
    e in Notary.DSL.Error -> {:error, e}
  end

  defp ensure_loaded(app) do
    case Application.load(app) do
      :ok ->
        :ok

      {:error, {:already_loaded, ^app}} ->
        :ok

      # The app isn't compiled yet (e.g. `mix notary.lock` early in a
      # consumer project's bootstrap, or the e2e fixture project mid-build):
      # its .app manifest doesn't exist, so no DSL modules can be discovered
      # and there is nothing to sync. A DSL module that DOES exist surfaces
      # as an ordinary compile error when the project builds, not here.
      {:error, {~c"no such file or directory", _manifest}} ->
        {:halted, []}

      {:error, reason} ->
        raise Notary.DSL.Error.new(
                "Could not load app #{inspect(app)} while looking for DSL spec modules: #{inspect(reason)}"
              )
    end
  end

  defp write_module(mod, specs_dir) do
    d = mod.__notary_description__()
    tla_text = Description.tla(d)
    cfg_text = Description.cfg(d)

    %{tla: tla_path, cfg: cfg_path} = paths(mod, specs_dir)

    written =
      [write_file(tla_path, tla_text), write_file(cfg_path, cfg_text)]
      |> Enum.map(fn
        {:written, path} -> path
        {:unchanged, _path} -> nil
      end)
      |> Enum.reject(&is_nil/1)

    written_names = Enum.map(written, &Path.basename/1)

    unchanged =
      [tla_path, cfg_path]
      |> Enum.reject(&(Path.basename(&1) in written_names))

    {written, unchanged}
  end

  defp write_file(path, text) do
    cond do
      not File.exists?(path) ->
        write!(path, text)
        {:written, path}

      generated?(path) and stale?(path, text) ->
        write!(path, text)
        {:written, path}

      generated?(path) ->
        {:unchanged, path}

      # No marker: a hand-written spec with this name. Never overwrite.
      true ->
        raise Notary.DSL.Error.new(
                "Refusing to write #{Path.relative_to_cwd(path)}: a hand-written file already exists there, " <>
                  "but a Notary.DSL module generates a spec of the same name. " <>
                  "Rename the DSL module (name: \"Other\") or remove the hand-written spec."
              )
    end
  end

  defp write!(path, text) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, text)
  end

  defp generated?(path),
    do: path |> File.read!() |> String.contains?(@marker_prefix)

  defp stale?(path, text),
    do: File.read!(path) != text

  @doc """
  The generated marker line for `source_module` — matched by `generated?/1`.
  Exposed for tests.
  """
  @spec marker(String.t()) :: String.t()
  def marker(source_module), do: @marker_prefix <> source_module
end
