defmodule Notary.DSL.Description do
  @moduledoc """
  The structured description gathered by `Notary.DSL` — the DSL-level
  equivalent of a `.tla` file — plus the emitter (`tla/1`, `cfg/2`) that
  turns it into `Name.tla` and `Name.cfg` text.

  The output is checked in, so TLC, the state graph, diagnostics, the lock
  file, and `mix notary.graph` all keep working on generated specs exactly as
  they do on hand-written ones. Generated files start with a
  `\* GENERATED by Notary.DSL ...` marker: `Notary.DSL.Compile` overwrites
  files carrying the marker and refuses to touch files that don't (a
  hand-written spec must never be clobbered by a name collision).
  """

  alias Notary.DSL.Error
  alias Notary.DSL.Expr

  @type domain ::
          {:enum, [Notary.DSL.Expr.t()]}
          | {:range, Notary.DSL.Expr.t(), Notary.DSL.Expr.t()}
          | {:boolean, nil}
          | nil

  @type constant :: %{
          required(:name) => String.t(),
          required(:value) => term(),
          required(:line) => non_neg_integer() | nil
        }

  @type variable :: %{
          required(:name) => String.t(),
          required(:type) => domain(),
          required(:line) => non_neg_integer() | nil
        }

  @type action :: %{
          required(:name) => String.t(),
          required(:params) => [%{required(:name) => String.t(), required(:domain) => domain()}],
          required(:guards) => [Notary.DSL.Expr.t()],
          required(:effects) => [Notary.DSL.Expr.t()],
          optional(:doc) => String.t() | nil,
          optional(:line) => non_neg_integer() | nil
        }

  @type assertion :: %{
          required(:name) => String.t(),
          required(:expr) => Notary.DSL.Expr.t(),
          optional(:doc) => String.t() | nil,
          optional(:line) => non_neg_integer() | nil
        }

  @type fairness :: %{required(:name) => String.t(), required(:strength) => :weak | :strong}

  @type t :: %__MODULE__{
          name: String.t(),
          source_module: String.t() | nil,
          doc: String.t() | nil,
          constants: [constant()],
          variables: [variable()],
          initial: %{String.t() => Notary.DSL.Expr.t()},
          actions: [action()],
          invariants: [assertion()],
          properties: [assertion()],
          fairness: [fairness()],
          raw_defs: [String.t()]
        }

  defstruct name: nil,
            source_module: nil,
            doc: nil,
            constants: [],
            variables: [],
            initial: %{},
            actions: [],
            invariants: [],
            properties: [],
            fairness: [],
            raw_defs: []

  # ---------------------------------------------------------------------------
  # Emission
  # ---------------------------------------------------------------------------

  @doc "The generated TLA+ module text for the description."
  @spec tla(t()) :: String.t()
  def tla(%__MODULE__{} = d) do
    d = complete_effects!(d)
    vars = Enum.map(d.variables, & &1.name)

    lines =
      [
        "\\* GENERATED by Notary.DSL — do not edit; source: #{d.source_module}",
        "---- MODULE #{d.name} ----"
      ] ++
        comments(d) ++
        decl_lines(d) ++
        def_block("TypeOK", type_ok_clauses(d), "/\\") ++
        def_block("Init", init_clauses(d), "/\\") ++
        Enum.flat_map(d.actions, &action_lines/1) ++
        Enum.flat_map(d.raw_defs, &[&1, ""]) ++
        def_block("Next", next_clauses(d), "\\/") ++
        Enum.flat_map(d.invariants, &assertion_lines/1) ++
        Enum.flat_map(d.properties, &assertion_lines/1) ++
        fairness_vars_defn(d, vars) ++
        def_block("Spec", spec_clauses(d, vars), "/\\") ++
        ["====="]

    lines
    |> Enum.map(&String.trim_trailing/1)
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  @doc """
  The generated TLC model (`Name.cfg`): the constants' model values, INIT/
  NEXT, invariants, properties, and `CHECK_DEADLOCK FALSE` when no action is
  unguarded (terminal states would otherwise be reported as deadlocks).
  """
  @spec cfg(t()) :: String.t()
  def cfg(%__MODULE__{} = d) do
    invariant_names = ["TypeOK" | Enum.map(d.invariants, & &1.name)]

    lines =
      ["\\* GENERATED by Notary.DSL — do not edit; source: #{d.source_module}"] ++
        ["\\* TLC model for #{d.name}. Keep constants small.", ""] ++
        Enum.map(d.constants, &"CONSTANT #{&1.name} = #{constant_value(&1.value)}") ++
        ["INIT Init", "NEXT Next", "INVARIANT #{Enum.join(invariant_names, " ")}"] ++
        property_lines(d) ++
        deadlock_line(d)

    Enum.join(lines, "\n") <> "\n"
  end

  defp comments(%__MODULE__{doc: nil}), do: []

  defp comments(%__MODULE__{doc: doc}),
    do: doc |> String.split("\n", trim: true) |> Enum.map(&("\\* " <> &1)) |> Enum.concat([""])

  # EXTENDS must come first (TLA+ requires it before CONSTANT/VARIABLES).
  defp decl_lines(d) do
    constants =
      case d.constants do
        [] -> []
        cs -> ["CONSTANT " <> Enum.map_join(cs, ", ", & &1.name)]
      end

    variables =
      case d.variables do
        [] -> []
        vs -> ["VARIABLES " <> Enum.map_join(vs, ", ", & &1.name)]
      end

    tail = if d.variables == [], do: [], else: [""]

    ["EXTENDS " <> Enum.join(extends(d), ", ")] ++ constants ++ variables ++ tail
  end

  defp extends(d) do
    terms = all_expr_terms(d)

    extensions =
      [
        {"Sequences", &sequence_used?/1},
        {"FiniteSets", &finite_sets_used?/1}
      ]
      |> Enum.filter(fn {_name, pred} -> Enum.any?(terms, pred) end)
      |> Enum.map(&elem(&1, 0))

    ["Naturals" | extensions]
  end

  defp sequence_used?({:call, name, _}), do: name in ["Head", "Tail", "Len", "SubSeq"]
  defp sequence_used?({:op, :concat, _}), do: true
  defp sequence_used?({:op, :index, _}), do: true
  defp sequence_used?(_), do: false

  defp finite_sets_used?({:call, "Cardinality", _}), do: true
  defp finite_sets_used?(_), do: false

  defp all_expr_terms(d) do
    (Enum.flat_map(d.variables, fn v ->
       case v.type do
         {:enum, items} -> items
         {:range, a, b} -> [a, b]
         _ -> []
       end
     end) ++
       Enum.flat_map(d.initial, &(elem(&1, 1) |> List.wrap())) ++
       Enum.flat_map(d.actions, &(&1.guards ++ &1.effects)) ++
       Enum.map(d.invariants, & &1.expr) ++
       Enum.map(d.properties, & &1.expr) ++
       Enum.flat_map(d.raw_defs, fn _ -> [] end))
    |> Enum.flat_map(&deep_terms/1)
  end

  defp deep_terms(term) do
    children =
      case term do
        {:op, _, args} -> args
        {:call, _, args} -> args
        {:enum, items} -> items
        {:seq, items} -> items
        {:record, fields} when is_map(fields) -> Map.values(fields)
        {:range, a, b} -> [a, b]
        {:assign, changes} -> Map.values(changes)
        {:temporal, _, args} -> args
        _ -> []
      end

    [term | Enum.flat_map(children, &deep_terms/1)]
  end

  defp type_ok_clauses(d) do
    for v <- d.variables do
      set =
        case v.type do
          {:boolean, nil} ->
            {:call, "BOOLEAN", []}

          {:enum, items} ->
            {:enum, items}

          {:range, a, b} ->
            {:range, a, b}

          nil ->
            raise Error,
              message:
                "Variable #{v.name} has no type; declare one (`variable #{v.name}: boolean`, " <>
                  "an enum list, or a range) so the generated TypeOK invariant is complete.",
              line: v[:line]
        end

      Expr.render({:op, :in, [{:var, v.name}, set]})
    end
  end

  defp init_clauses(d) do
    missing = for v <- d.variables, not Map.has_key?(d.initial, v.name), do: v.name

    if missing != [] do
      raise Error,
        message:
          "initial/1 must give a starting value for every variable; missing: #{Enum.join(missing, ", ")}."
    end

    extra = Map.keys(d.initial) -- Enum.map(d.variables, & &1.name)

    if extra != [] do
      raise Error,
        message:
          "initial/1 sets names that are not declared variables: #{Enum.join(extra, ", ")}."
    end

    for {name, value} <- Enum.sort(d.initial) do
      "#{name} = #{Expr.render(value)}"
    end
  end

  defp action_lines(%{name: name, doc: doc} = a) do
    head = action_head(a)

    doc_lines =
      case doc do
        nil -> []
        doc -> String.split(doc, "\n", trim: true) |> Enum.map(&("\\* " <> &1))
      end

    guard_clauses = Enum.map(a.guards, &Expr.render/1)
    effect_clauses = Enum.flat_map(a.effects, &effect_clauses/1)
    clauses = guard_clauses ++ effect_clauses

    if clauses == [] do
      raise Error,
        message: "Action #{name} has no effect: it must assign or declare unchanged variables.",
        line: Map.get(a, :line)
    end

    body = vertical(head, clauses, "/\\")

    doc_lines ++ [body, ""]
  end

  # TLA+ actions must specify the complete next state: a variable neither
  # assigned nor declared UNCHANGED leaves `step'` unconstrained (TLC:
  # "Successor state is not completely specified"). By default the DSL closes
  # the gap for you — any variable the action doesn't mention gets an
  # `UNCHANGED` clause — since "what stays" is mechanical given the full
  # variable list. Pass `explicit_unchanged: true` per action (or per module
  # in `use Notary.DSL, explicit_unchanged: true`) to write `unchanged/1`
  # yourself and have missing variables fail compilation instead.
  defp complete_effects!(%__MODULE__{} = d) do
    var_names = d.variables |> Enum.map(& &1.name) |> MapSet.new()

    actions =
      for a <- d.actions do
        a =
          if Map.get(a, :explicit_unchanged, false),
            do: a,
            else: Map.update!(a, :effects, fn effects -> Enum.map(effects, &close_branches/1) end)

        touched = Enum.flat_map(a.effects, &effect_touched_vars/1) |> MapSet.new()
        untouched = var_names |> MapSet.difference(touched) |> MapSet.to_list() |> Enum.sort()

        cond do
          Map.get(a, :explicit_unchanged, false) and untouched != [] ->
            raise Error,
              message:
                "Action #{a.name} does not say what happens to " <>
                  still_missing(untouched) <>
                  ". With explicit_unchanged, every variable must be covered: add " <>
                  "`assign(#{hd(untouched)}: ...)` or `unchanged([...])` for what stays.",
              line: Map.get(a, :line)

          Map.get(a, :explicit_unchanged, false) ->
            a

          untouched == [] ->
            a

          true ->
            Map.put(a, :effects, a.effects ++ [{:unchanged, untouched}])
        end
      end

    %__MODULE__{d | actions: actions}
  end

  defp still_missing([one]), do: "variable #{one}"
  defp still_missing(many), do: "variables #{Enum.join(many, ", ")}"

  # Variables an effect fully determines. A conjunction determines everything
  # its parts do; a disjunction (`either`, or an `if` whose branches assign)
  # only what EVERY branch determines, since TLC takes one branch per step.
  defp effect_touched_vars({:assign, changes}), do: Map.keys(changes)
  defp effect_touched_vars({:unchanged, names}), do: names

  defp effect_touched_vars({:op, :parallel, args}),
    do: Enum.flat_map(args, &effect_touched_vars/1) |> Enum.uniq()

  defp effect_touched_vars({:op, op, _} = term) when op in [:choice, :if] do
    term
    |> branches()
    |> Enum.map(&MapSet.new(effect_touched_vars(&1)))
    |> Enum.reduce(&MapSet.intersection/2)
    |> MapSet.to_list()
  end

  defp effect_touched_vars(_), do: []

  # Auto-UNCHANGED inside branches: each branch of an `either`/`if` gets an
  # UNCHANGED for the variables a sibling branch assigns but it doesn't, so
  # `either(assign(x: 1), assign(y: 2))` becomes
  # `(x' = 1 /\ UNCHANGED y) \/ (y' = 2 /\ UNCHANGED x)` rather than leaving
  # y (or x) unconstrained in one branch.
  defp close_branches({:op, :parallel, args}),
    do: {:op, :parallel, Enum.map(args, &close_branches/1)}

  defp close_branches({:op, op, _} = term) when op in [:choice, :if] do
    closed = term |> branches() |> Enum.map(&close_branches/1)

    if Enum.any?(closed, &has_effect?/1) do
      all = closed |> Enum.flat_map(&effect_touched_vars/1) |> Enum.uniq()

      closed =
        Enum.map(closed, fn branch ->
          case all -- effect_touched_vars(branch) do
            [] -> branch
            missing -> {:op, :parallel, [branch, {:unchanged, Enum.sort(missing)}]}
          end
        end)

      put_branches(term, closed)
    else
      term
    end
  end

  defp close_branches(term), do: term

  defp branches({:op, :choice, args}), do: args
  defp branches({:op, :if, [_cond, t, e]}), do: [t, e]

  defp put_branches({:op, :choice, _}, args), do: {:op, :choice, args}
  defp put_branches({:op, :if, [c, _, _]}, [t, e]), do: {:op, :if, [c, t, e]}

  defp has_effect?({:assign, _}), do: true
  defp has_effect?({:unchanged, _}), do: true
  defp has_effect?({:op, _, args}) when is_list(args), do: Enum.any?(args, &has_effect?/1)
  defp has_effect?(_), do: false

  # `Next` disjunction. Parameterized actions get an existential per param,
  # quantified over the param's declared domain (`\E param \in 1..2 :
  # Deposit(param)`); TLC's action-labelled dot dump strips the arguments, so
  # the state graph's edge label is `Deposit` either way.
  defp next_clauses(d) do
    Enum.map(d.actions, fn a ->
      case a.params do
        [] ->
          a.name

        params ->
          quants =
            params
            |> Enum.map(fn p ->
              dom = param_domain(p)
              "\\E #{p.name} \\in #{dom} : "
            end)
            |> Enum.join()

          "#{quants}#{a.name}(#{Enum.map_join(a.params, ", ", & &1.name)})"
      end
    end)
  end

  defp param_domain(%{domain: nil}) do
    raise Error,
      message:
        "A parameterized action's param needs a domain (e.g. `action Deposit, param: 1..2`) so Next can quantify over it."
  end

  defp param_domain(%{domain: {:enum, items}}), do: Expr.render({:enum, items})
  defp param_domain(%{domain: {:range, a, b}}), do: Expr.render({:range, a, b})
  defp param_domain(%{domain: {:boolean, nil}}), do: "BOOLEAN"

  defp param_domain(%{domain: {:record, _}}),
    do:
      raise(Error,
        message: "Record domains are not supported for action parameters; use an enum or range."
      )

  defp action_head(%{name: name, params: params}) do
    case params do
      [] -> "#{name} =="
      ps -> "#{name}(#{Enum.map_join(ps, ", ", & &1.name)}) =="
    end
  end

  # An effect term renders to one or more clause lines: an `assign` with
  # several variables yields one `x' = ...` clause per variable (joined by
  # `/\` at the chain level, like any hand-written action); `unchanged`
  # yields its UNCHANGED clause; anything else (e.g. an `if` whose branches
  # assign different variables) renders on one line.
  defp effect_clauses({:assign, changes}),
    do: for({name, value} <- Enum.sort(changes), do: "#{name}' = #{Expr.render(value)}")

  defp effect_clauses({:unchanged, names}),
    do: [Expr.render({:unchanged, names})]

  defp effect_clauses(term), do: [Expr.render(term)]

  # WF_/SF_ subscripts name the `vars` operator; define it only when needed
  # (a bare `vars` definition is fine too, but unused decls are noise).
  defp spec_clauses(d, vars) do
    subscript =
      case vars do
        [] ->
          raise Error, message: "A spec needs at least one variable."

        [one] when is_binary(one) ->
          one

        many when is_list(many) ->
          "<<#{Enum.join(many, ", ")}>>"
      end

    base = "Init /\\ [][Next]_#{subscript}"

    conjuncts =
      Enum.map(d.fairness, fn %{name: name, strength: strength} ->
        prefix = if strength == :weak, do: "WF", else: "SF"
        "#{prefix}_vars(#{name})"
      end)

    [base | conjuncts]
  end

  # `vars == <<...>>` is emitted in front of Spec when the spec has fairness,
  # because WF_vars/SF_vars reference it.
  defp fairness_vars_defn(d, vars) do
    if d.fairness == [] or vars == [] do
      []
    else
      ["vars == <<#{Enum.join(vars, ", ")}>>", ""]
    end
  end

  defp assertion_lines(%{name: name, doc: doc} = a) do
    doc_lines =
      case doc do
        nil -> []
        doc -> String.split(doc, "\n", trim: true) |> Enum.map(&("\\* " <> &1))
      end

    doc_lines ++ ["#{name} ==", body("     ", Expr.render(a.expr)), ""]
  end

  defp property_lines(d) do
    case d.properties do
      [] -> []
      props -> ["PROPERTY #{Enum.map_join(props, " ", & &1.name)}"]
    end
  end

  defp deadlock_line(d) do
    unguarded = Enum.any?(d.actions, &(&1.guards == []))

    if unguarded do
      []
    else
      # Every action is guarded, so finite models can reach states where
      # nothing is enabled; TLC calls that a deadlock even though it is the
      # spec's own intent (Greeter: nothing left to do). The DSL knows the
      # difference between "the spec intends a stop" and "the code hangs"
      # only via invariants/properties, so disable the deadlock check here.
      ["CHECK_DEADLOCK FALSE"]
    end
  end

  # TLC cfg constant values are Elixir terms rendered as TLA+ literals.
  defp constant_value(v) when is_integer(v), do: Integer.to_string(v)
  defp constant_value(true), do: "TRUE"
  defp constant_value(false), do: "FALSE"
  defp constant_value(v) when is_binary(v), do: inspect(v)

  defp constant_value(v) when is_list(v) do
    if Keyword.keyword?(v) do
      v
      |> Enum.map(fn {k, val} -> "#{k} |-> #{constant_value(val)}" end)
      |> Enum.join(", ")
      |> then(&"[#{&1}]")
    else
      v |> Enum.map(&constant_value/1) |> Enum.join(", ") |> then(&"<<#{&1}>>")
    end
  end

  defp constant_value(%{} = v),
    do:
      v
      |> Enum.sort()
      |> Enum.map(fn {k, val} -> "#{k} |-> #{constant_value(val)}" end)
      |> Enum.join(", ")
      |> then(&"[#{&1}]")

  defp constant_value({:model, name}) when is_atom(name), do: Atom.to_string(name)

  defp constant_value(v),
    do: raise(Error, message: "Cannot render constant value: #{inspect(v)}")

  # A definition block: `Name ==` with the clauses laid out vertically, plus
  # a blank line after (a single clause inlines on the definition line).
  defp def_block(_name, [], _sep), do: []

  defp def_block(name, clauses, sep) do
    [vertical("#{name} ==", clauses, sep), ""]
  end

  # -- layout ------------------------------------------------------------------

  # `head` followed by the first clause, then the rest of the clauses each on
  # its own line with the separator, aligned under the first clause:
  #
  #     Greet == /\ greeted = FALSE
  #              /\ greeted' = TRUE
  #
  # A single clause stays unprefixed (`Reset == count' = 0`).
  @spec vertical(String.t(), [String.t()], String.t()) :: String.t()
  defp vertical(head, [single], _sep), do: "#{head} #{single}"

  defp vertical(head, clauses, sep) do
    pad = String.duplicate(" ", String.length(head) + 1)
    [first | rest] = clauses

    "#{head} #{sep} #{first}\n" <>
      Enum.map_join(rest, "\n", &"#{pad}#{sep} #{&1}")
  end

  # Wraps a (possibly multiline) body once: every line after the first is
  # indented by `pad`.
  defp body(pad, text) do
    case String.split(text, "\n") do
      [one] -> one
      [first | rest] -> "#{first}\n" <> Enum.map_join(rest, "\n", &(pad <> &1))
    end
  end
end
