defmodule Notary.DSL.SyncTest do
  use ExUnit.Case, async: false

  @moduletag :tmp_dir

  alias Notary.DSL.Compile

  @probe Notary.DSL.SyncTestProbe

  @dsl_source """
  defmodule Notary.DSL.SyncTestProbe do
    use Notary.DSL, name: "SyncTestProbe"

    description "A probe spec compiled from a string inside the sync test."

    variable ready: boolean()
    initial ready: false

    action Flip do
      guard ready == false
      assign ready: true
    end
  end
  """

  setup %{tmp_dir: dir} do
    specs = Path.join(dir, "specs")
    File.mkdir_p!(specs)
    ensure_probe()
    %{specs: specs}
  end

  defp ensure_probe do
    unless Code.ensure_loaded?(@probe) do
      Code.compile_string(@dsl_source)
    end

    :ok
  end

  test "sync writes the generated files and is idempotent", %{specs: specs} do
    assert {:ok, written, unchanged} = Compile.sync_modules([@probe], specs_dir: specs)

    names = Enum.map(written, &Path.basename/1)
    assert "SyncTestProbe.tla" in names
    assert "SyncTestProbe.cfg" in names
    assert unchanged == []

    # Marker present; source module named.
    text = File.read!(Path.join(specs, "SyncTestProbe.tla"))
    assert text =~ "GENERATED by Notary.DSL"
    assert text =~ "Notary.DSL.SyncTestProbe"

    # Second sync: nothing written, everything unchanged.
    assert {:ok, [], unchanged2} = Compile.sync_modules([@probe], specs_dir: specs)
    assert length(unchanged2) == 2
  end

  test "sync refuses to overwrite a hand-written spec of the same name", %{specs: specs} do
    File.write!(Path.join(specs, "SyncTestProbe.tla"), "---- MODULE SyncTestProbe ----\n=====\n")

    assert_raise Notary.DSL.Error, ~r/Refusing to write/, fn ->
      Compile.sync_modules([@probe], specs_dir: specs)
    end
  end
end
