defmodule Notary.DSL.SmokeTest do
  use ExUnit.Case, async: false

  alias Notary.DSL.Description

  defmodule SmokeGreeter do
    use Notary.DSL, name: "SmokeGreeter"

    description("Greeter: says hello exactly once.")

    variable(greeted: boolean())

    initial(greeted: false)

    action Greet do
      guard(greeted == false)
      assign(greeted: true)
    end
  end

  defmodule SmokeCounter do
    use Notary.DSL, name: "SmokeCounter"

    description("A bounded counter with reset.")

    constant(max: 3)

    variable(x: 0..max)

    initial(x: 0)

    action Inc do
      guard(x < max)
      assign(x: x + 1)
    end

    action Reset do
      assign(x: 0)
    end
  end

  defmodule SmokeWizard do
    use Notary.DSL, name: "SmokeWizard"

    variable(step: ["address", "payment", "done"])
    variable(address: boolean())

    initial(step: "address", address: false)

    action EnterAddress, doc: "Record that an address exists." do
      guard(step == "address")
      assign(address: true)
    end

    action Continue do
      guard(step == "address" and address)
      assign(step: "payment")
    end

    action Back do
      guard(step == "payment")
      assign(step: "address")
    end
  end

  test "greeter emits the expected module" do
    out = Description.tla(SmokeGreeter.__notary_description__())

    assert out == """
           \\* GENERATED by Notary.DSL — do not edit; source: Notary.DSL.SmokeTest.SmokeGreeter
           ---- MODULE SmokeGreeter ----
           \\* Greeter: says hello exactly once.

           EXTENDS Naturals
           VARIABLES greeted

           TypeOK == greeted \\in BOOLEAN

           Init == greeted = FALSE

           Greet == /\\ greeted = FALSE
                    /\\ greeted' = TRUE

           Next == Greet

           Spec == Init /\\ [][Next]_greeted

           =====
           """
  end

  test "counter emits constants, ranges and primed arithmetic" do
    out = Description.tla(SmokeCounter.__notary_description__())
    cfg = Description.cfg(SmokeCounter.__notary_description__())

    assert out =~ "CONSTANT max"
    assert out =~ "x \\in 0..max"
    assert out =~ "x' = x + 1"

    assert cfg =~ "CONSTANT max = 3"
  end

  test "wizard emits actions and doc comments" do
    out = Description.tla(SmokeWizard.__notary_description__())

    assert out =~ ~s(step \\in {"address", "payment", "done"})
    assert out =~ ~s(Continue == /\\ step = "address")
    assert out =~ "\\* Record that an address exists."
  end

  test "auto-UNCHANGED: actions not mentioning a variable get UNCHANGED clauses" do
    out = Description.tla(SmokeWizard.__notary_description__())

    assert out =~ "step' = \"payment\""
    assert out =~ "UNCHANGED address"
  end

  test "get/1 in an assign value fails with a helpful error" do
    assert_raise Notary.DSL.Error,
                 ~r/get\(x\) is not allowed/,
                 fn ->
                   defmodule BadGet do
                     use Notary.DSL, name: "BadGet", generate: false
                     variable(x: 0..9)
                     initial(x: 0)

                     action Inc do
                       assign(x: get(x) + 1)
                     end
                   end
                 end
  end

  test "guarded-only actions note deadlock disabled" do
    cfg = Description.cfg(SmokeGreeter.__notary_description__())
    assert cfg =~ "CHECK_DEADLOCK FALSE"

    # SmokeCounter's Reset is unguarded, so no deadlock disabling needed.
    cfg2 = Description.cfg(SmokeCounter.__notary_description__())
    refute cfg2 =~ "CHECK_DEADLOCK"
  end
end
